config/routes.rb
Rails.application.routes.draw do

  resources :apns, only: [:new, :create, :show, :index, :edit, :update]
  resources :apns do
    resources :contacts
    resources :nodes do
      resources :tunnels do
        resources :tunnel_rules
        end
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:create, :destroy, :new]
  resources :users do
    member do
      get :activate
    end
  end

  root 'apns#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get "signup" => "users#new", :as => "signup"
  get 'deletenode' => 'nods#destroy',:as => 'deletenode'

end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :apn
  has_many :tunnels, :dependent => :destroy
  accepts_nested_attributes_for :tunnels, allow_destroy: true
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # this is a CanCan thing, to check to see if you're logged in before you can do anything on this page.
  load_and_authorize_resource

  # required to be logged in to be able to see the page.
  before_action :require_login
  def index
    # make sure that you are seeing the APN that the Node belongs to
    @apn = Apn.find(params[:apn_id])
    @nodes = @apn.nodes.order(id: :asc).all
  end
  def show
    @nodes = Node.order(id: :asc).all
  end

  def new
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    # makes sure that when you create a new node that you pass in the APN ID into the @node
    @node = @apn.nodes.build
  end

  def create
    # makes sure that you find the right APN ID for that new node first
    @apn = Apn.find(params[:apn_id])
    # make sure that when you create a new node that you pass in the APN ID into the @node (note it says nodes and not node) You'll be passing the contact_params method
    @node = @apn.nodes.build(node_params)
    if @node.save
      redirect_to apn_nodes_path
    else
      render :new
    end
  end
  def edit
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    @node = @apn.nodes.find(params[:id])
  end

  def update
    @node = Node.find(params[:id])

    if @node.update_attributes(node_params)
      redirect_to apn_nodes_path, notice: 'Successfully Updated the Node Information'
    end
  end

  def destroy
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    @node = @apn.nodes.find(params[:id])
    @node.destroy
    redirect_to apn_nodes_path, notice: 'Node was deleted'
  end

  private

  def node_params
    params.require(:node).permit(
        :ssr_location,
        tunnels_attributes: [
            :id,
            :nat_server_ip,
            :customer_vpn_ip,
            :customer_server_ip,
            :rogers_vpn_ip,
            :rogers_mobile_ip,
            :rogers_gre_tunnel_ip,
            :customer_gre_tunnel_ip,
            :roger_vpn_device_desc,
            :customer_vpn_device_desc,
            :rogers_vpn_device_version,
            :customer_vpn_device_version,
            :rogers_encryption_domain,
            :customer_encryption_domain,
            :_destroy
        ]
    )
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_tunnel_fields.html.erb
<div class="tunnel">
  <p>
    <%= f.label :rogers_mobile_ip, "Mobile Device IP range:" %>
    <%= f.text_field :rogers_mobile_ip %>
    For GRE Based APN, please choose your own IP address range<br>

    For iMPLS-Based APNs (i.e., AS812), please choose your own IP address range, except the range 192.168.0.0/16.<br>

    For APNs without GRE, specify how many IP’s are required.  Device IP addresses will be assigned from the 10.100.0.0/16 to 10.217.0.0/16 IP range by Rogers.<br>

    If any part of this address ranges conflict with your network, please Source NAT to adequate address range.<br>
  </p>
  <p>
    <%= f.label :customer_server_ip, "Destination/Server IP addresses:" %>
    <%= f.text_field :customer_server_ip %>
    For GRE APNs, destination addresses will be the Customer GRE Physical Endpoints.<br>

    For APNs without GRE will use private IPs assigned from the 10.100.0.0/16 to 10.217.0.0/16 IP range by Rogers unless public IP’s are provided.<br>

    For AS812 MPLS Links All of the customer’s server IP’s are reachable<br>

    Note:  The customer can create a 1:1 NAT to access the real addresses of their hosts/servers.)<br>

    Note:<br>
    -	If you supply Rogers with Public IP addresses for your servers you will not be able to connect to those servers from ANY GPRS Internet services (Internet.com or VPN.com) provided by Rogers Wireless once the routing work orders are implemented.  If you are currently running your application on either of these 2 Internet services and wish to have NO service interruptions please make this known to a Rogers Wireless Technical Services Consultant.<br>
    -	Rogers Wireless will not allow routing of any Public IP through a VPN tunnel that is not exclusively owned and used by the customer.<br>

  </p>
  <% if current_user.administrator? %>
      <p>
        Rogers VPN tunnel IP:<br>
          <%= f.select :rogers_vpn_ip, options_for_select([
                                                                 "74.198.28.1 Toronto",
                                                                 "74.198.64.1 Montreal",
                                                                 "74.198.148.1 Vancouver"
                                                         ])%>
          </p>

  <% end %>
      <p>
        <%= f.label :customer_vpn_ip, "Customer VPN Device IP Address:" %>
        <%= f.text_field :customer_vpn_ip %>
      <p>
      <p>
        <%= f.label :customer_vpn_device_desc, "Customer VPN Device Description:" %>
        <%= f.text_field :customer_vpn_device_desc %>
      <p>
      <p>
        <%= f.label :customer_vpn_device_version, "Customer VPN Device Version:" %>
        <%= f.text_field :customer_vpn_device_version %>
      <p>
        <% if current_user.administrator? %>
      <p>
        <%= f.label :rogers_encryption_domain, "Rogers Encryption Domain:" %>
        <%= f.text_field :rogers_encryption_domain %>
      <p>
      <p>
        <%= f.label :customer_encryption_domain, "Customer Encryption Domain:" %>
        <%= f.text_field :customer_encryption_domain %>
      <p>
        <% end %>

      <%= link_to_remove_association "Remove Tunnel Information", f, wrapper_class: 'tunnel' %>
    </p>
</div>

app/views/nodes/destroy.html.erb
<h1>Nodes#destroy</h1>
<p>Find me in app/views/nodes/destroy.html.erb</p>

app/views/nodes/edit.html.erb
<h1>Select a NODE</h1>
<!--passed in an array that takes the @apn (:apn_id), @contact objects there were declared from the node controller def new -->
<div class="row">
  <div class="large-6 columns">
    <%= form_for [@apn, @node] do |f| %>
        Rogers NODE Location<br>
        <%= f.select :ssr_location, options_for_select([
                                                               "Toronto",
                                                               "Montreal",
                                                               "Vancouver"
                                                       ])%>
        <p>
          <!--this code below is a nested cocoon form for tunnels-->
          Tunnel Information:<br>
          <%= f.fields_for :tunnels do |tunnel| %>
              <% render "tunnel_fields", f: tunnel %>
          <% end %>
          <!--link_to_add_association is a cocoon method for this adding a nested form-->
          <%= link_to_add_association "Add Tunnel", f, :tunnels %>
        </p>
        <%= f.submit "Edit Select Node"%>
    <% end %>

    <%= button_to "Back", apn_nodes_url, :method => "get" %>
  </div>
</div>

app/views/nodes/index.html.erb
<h1>Node Information for APN:<%= @apn.apn_name %></h1>

<div class="row">
  <div class="large-6 columns">
    <ul>
      <table class="Node Table">
        <thead>
        <th>Node Name:</th>
        <th>Edit APN Node Information:</th>
        <th>Delete Node</th>
        </thead>
        <tbody>
        <% @nodes.each do |n| %>
            <tr>
              <td><%= n.ssr_location %></td>
              <td><%= button_to "Edit Node" , edit_apn_node_path(n.apn_id, n.id), :method => "get" %></td>
              <td><%= button_to "Delete", apn_node_path(n.apn_id, n.id), :confirm => "Are you sure you want delete this node?", :method => "delete"%></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= button_to "Add Node", new_apn_node_path(@apn), :method => "get" %>
    </ul>
    <%= button_to "Back", apns_url, :method => "get" %>
  </div>
</div>

app/views/nodes/new.html.erb
<h1>Select a NODE</h1>
<!--passed in an array that takes the @apn (:apn_id), @contact objects there were declared from the node controller def new -->
<div class="row">
  <div class="large-6 columns">
    <%= form_for [@apn, @node] do |f| %>
        Rogers NODE Location:<br>
        <%= f.select :ssr_location,  options_for_select([
                                                               "Toronto",
                                                               "Montreal",
                                                               "Vancouver"
                                                       ])%>

        <p>
          <!--this code below is a nested cocoon form for tunnels-->
          Tunnel Information:<br>
          <%= f.fields_for :tunnels do |tunnel| %>
              <% render "tunnel_fields", f: tunnel %>
          <% end %>
          <!--link_to_add_association is a cocoon method for this adding a nested form-->
          <%= link_to_add_association "Add Tunnel", f, :tunnels %>
        </p>
        <%= f.submit "Select/Save Node"%>
    <% end %>
  </div>

  <%= button_to "Back", apn_nodes_url, :method => "get" %>
</div>

app/views/nodes/show.html.erb
<h1>Nodes#show</h1>
<p>Find me in app/views/nodes/show.html.erb</p>