config/routes.rb
Rails.application.routes.draw do

  resources :apns, only: [:new, :create, :show, :index, :edit, :update]
  resources :apns do
    resources :contacts
    resources :nodes do
      resources :tunnels do
        resources :tunnel_rules
        end
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:create, :destroy, :new]
  resources :users do
    member do
      get :activate
    end
  end

  root 'apns#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get "signup" => "users#new", :as => "signup"
  get 'deletenode' => 'nods#destroy',:as => 'deletenode'

end

app/models/apn.rb
class Apn < ActiveRecord::Base
  belongs_to :user
  has_many :nodes, :dependent => :destroy
  has_many :contacts, :dependent => :destroy
  accepts_nested_attributes_for :contacts, :nodes, allow_destroy: true
end

app/controllers/apns_controller.rb
class ApnsController < ApplicationController
  # this is a CanCan thing, to check to see if you're logged in before you can do anything on this page.
  load_and_authorize_resource

  # required to be logged in to be able to see the page.
  before_action :require_login



  def index
    # ensures that when you display @apns it's in the order by the apn.id
    @apns = Apn.order(id: :asc).all
  end

  def show
    # ensures that when you display @apns it's in the order by the apn.id
    @apns = Apn.order(id: :asc).all
    @contacts = Contact.order(id: :asc).all
    @node = Node.order(id: :asc).all
  end

  def edit
    @apn = Apn.find(params[:id])
  end

  def update
    @apn = Apn.find(params[:id])

    if @apn.update_attributes(apn_params)
      redirect_to apns_path, notice: 'Successfully Updated the APN'
    else
      render :edit
    end
  end

  def new
    @apn = Apn.new
  end

  def create
    @apn = Apn.new(apn_params)
    # ensures that when you save that the @apn.user ID is will be saved with the current_user's user.id
    @apn.user = current_user

    if @apn.save
      redirect_to apns_path
    else
      render :new
    end
  end

  private

  def apn_params
    params.require(:apn).permit(
                            :apn_name,
                            :project_name,
                            :project_number,
                            :rogers_apn_id,
                            :fido_apn_id,
                            :msd_code,
                            :static_ip,
                            :control_center,
                            :context_id,
                            :control_center_account_name,
                            :control_center_account_id,
                            :primary_dns,
                            :secondary_dns,
                            :redundancy_type,
                            :m2m_communications,
                            :radius_jasper_proxy_filter,
                            :company_name,
                            #makes sure that I can nest the contact model into the apn form
                            contact_attributes: [
                                :first_name,
                                :last_name,
                                :company_name,
                                :street_address,
                                :city,
                                :province_state,
                                :country,
                                :email,
                                :phone_number1,
                                :phone_number2,
                                :technical_contact,
                                :business_contact
                            ],
                            node_attributes:[
                                :ssr_location
                            ]
    )
  end
end

app/helpers/apns_helper.rb
module ApnsHelper
end

app/views/apns/_contact_fields.html.erb
<div class="contact">
      <p>
        <%= f.label :business_contact %>
        <%= f.check_box :business_contact %>
      </p>
      <p>
        <%= f.label :technical_contact %>
        <%= f.check_box :technical_contact %>
      </p>
      <p>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </p>
      <p>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </p>
      <p>
        <%= f.label :company_name %>
        <%= f.text_field :company_name %>
      </p>
      <p>
        <%= f.label :street_address %>
        <%= f.text_field :street_address %>
      </p>
      <p>
        <%= f.label :city %>
        <%= f.text_field :city %>
      </p>
      <p>
        <%= f.label :province_state %>
        <%= f.text_field :province_state %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label 'Main Phone' %>
        <%= f.text_field :phone_number1 %>
      </p>
      <p>
        <%= f.label 'Cell Phone' %>
        <%= f.text_field :phone_number2 %>
      </p>
      <%= link_to_remove_association "Remove Contact", f, wrapper_class: 'contact' %>
</div>

app/views/apns/_node_fields.html.erb
<div class="node">
  Please select a NODE for
  <%= f.select :ssr_location, options_for_select([
                                                            "Toronto",
                                                            "Montreal",
                                                            "Vancouver"
                                                    ])%>

  <p>
    <!--this code below is a nested cocoon form for tunnels-->
    Tunnel Information:<br>
    <%= f.fields_for :tunnels do |tunnel| %>
        <% render "tunnel_fields", f: tunnel %>
    <% end %>
    <!--link_to_add_association is a cocoon method for this adding a nested form-->
    <%= link_to_add_association "Add Tunnel", f, :tunnels %>
  </p>
  <%= link_to_remove_association "Remove Node", f, wrapper_class: 'node' %>
</div>

app/views/apns/edit.html.erb
<h1>Edit Custom APN Form</h1>
<p>Please fill out the sections below</p>

<%= form_for @apn do |f| %>
    <% if @apn.errors.any? %>
        <div class="error_messages">
          <h2>Apn Form is invalid</h2>
          <ul>
            <% for message in @apn.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :company_name, 'Company Name' %>
      <%= f.text_field :company_name %>
    </p>
    <p>
      <%= f.label :project_name, 'Project Name' %>
      <%= f.text_field :project_name %>
    </p>
    <p>
      <%= f.label :project_number, 'Project Number' %>
      <%= f.text_field :project_number %>
    </p>

    <p>
      <%= f.label :apn_name, "APN Name" %>
      <%= f.text_field :apn_name %>
    </p>
    <p>
      <%= f.label :static_ip, "Static IP Required?" %>
      <%= f.check_box :static_ip %>
    </p>
    <p>
      <%= f.label :control_center, "Control Center Required?" %>
      <%= f.check_box :control_center %>

    </p>
    <% if current_user.administrator? %>
        <p>
          <%= f.label :control_center_account_name, "Control Center Account Name:" %>
          <%= f.text_field :control_center_account_name %>
        </p>
        <p>
          <%= f.label :control_center_account_id, "Control Center Account ID:" %>
          <%= f.text_field :control_center_account_id %>
        </p>
        <p>
          <%= f.select :radius_jasper_proxy_filter, options_for_select([
                                                                               "Default: Forward Radius traffic to Control Centre based on Jasper dedicated IMSIs only",
                                                                               "Change: Modify Radius to add IMSI filtering for Jasper"
                                                                       ])%>
    <% end %>
    <p>
      Please select from one of the types of mobile to mobile communications:<br>
      <%= f.select :m2m_communications, options_for_select([
                                                                   "Mobile to Mobile Communication is Denied (Default)",
                                                                   "Mobile to Mobile Communication is Required"
                                                           ])%>
    </p>
    <% if current_user.administrator? %>
        <p>
          (To be filled out by Rogers)
          <%= f.label :rogers_apn_id, "Rogers APN ID" %>
          <%= f.text_field :rogers_apn_id %>
        </p>
        <p>
          <%= f.label :fido_apn_id, "Fido APN ID (5000+Rogers APN ID):" %>
          <%= f.text_field :fido_apn_id %>
        </p>
        <p>
          <%= f.label :msd_code,"MSD Code" %>
          <%= f.text_field :msd_code %>
        </p>

        <p>
          <%= f.label :context_id, "Context ID" %>
          <%= f.text_field :context_id %>
          Max download rate: 250000000<br>
          Max upload rate: 100000000<br>
          QoS profile (HSS-EsmQosProfileQci): 8<br>
          Priority (HSS-EsmQosProfileArp): 10<br>
          Charging Chars (HSS-EsmEpsBearerChargingChars) : 9<br>
          PDN Type: V4  OR V6 or Dual stack V4V6 <br>

        </p>
    <% end %>
    <h3>Select Redundancy Type:</h3>

    Select one of the following designs…<br>
    <br>
    Note:  Please ensure a discussion has taken place with regards to the type of redundancy required.<br>
    Note: Please fill out BGP/GRE form in Appendix if applicable.<br>
    When 2 GGSNs are used in an APN design they will automatically take over from each other should a device not be able to establish a PDP context (initiate a data session) <br>
    <br>
        <%= f.select :redundancy_type, options_for_select([
                                                                  "1 GGSN/SSR, 1 Egress Point, GRE, Static Source Routing",
                                                                  "1 GGSN/SSR, 1 Egress Point, GRE, BGP Routing",
                                                                  "1 GGSN/SSR, 1 Egress Point, NO GRE, Static Destination Routing",
                                                                  "1 GGSN/SSR, 2 Egress Points to Separate Networks, Not Redundant, GRE, BGP Routing",
                                                                  "1 GGSN/SSR, 2 Egress Points to Separate Networks, NO GRE, Static Destination Routing",
                                                                  "1 GGSN/SSR, 2 Egress Points to (Redundant Links), GRE, BGP Routing",
                                                                  "2 GGSNs/SSRs, 1 Egress Point, GRE, Static Source Routing",
                                                                  "2 GGSNs/SSRs, 1 Egress Point, GRE, BGP Routing",
                                                                  "2 GGSNs/SSRs, 1 Egress Point, NO GRE, Destination Routing",
                                                                  "2 GGSNs/SSRs, 2 Egress Points per GGSN/SSR to Separate Networks, Data Paths Not Redundant, GRE, BGP, Routing",
                                                                  "2 GGSNs/SSRs, 2 Egress Points per GGSN/SSR to Separate Networks, Data Paths Not Redundant, No GRE, Static Destination Routing",
                                                                  "2 GGSNs/SSRs, 2 Egress Points per GGSN/SSR (Redundant Links), GRE, BGP Routing",
                                                                  "Other Design"
                                                          ])%>




    <%= f.submit "Submit" %>
    <%= button_to "Cancel", apns_url, :method => "get" %>
<% end %>

app/views/apns/index.html.erb
<h1>APN Index</h1>
<!--check to see if the current user is an adminstrator-->
<% if current_user.administrator? %>
    <div>Index of all APN's</div>
<% else %>
    <!--if you are a user you should only see your APN's-->
    <div>Index of all owned APN's</div>
<% end %>
<hr>

<div class="row">
  <div class="large-6 columns">
    <ul>
      <table class="APN Table">
          <thead>
              <th>APN Name</th>
              <th>Project Name</th>
              <th>APN Information</th>
              <th>Edit APN Information</th>
              <th>APN Contacts</th>
              <th>APN Node Information</th>
          </thead>
          <tbody>
          <% @apns.each do |apn| %>
              <!--checks to see if the current user can each specific @apn object, if you do this again, make sure that you've passed in a specific object and not just the Class-->
              <% if can?(:read, apn) %>
                <tr>
                  <td><%= apn.apn_name %></td>
                  <td><%= apn.project_name  %></td>
                  <td><%= button_to "APN Page", apn_url(apn.id), :method => "get" %></td>
                  <td><%= button_to "Edit APN" , edit_apn_url(apn.id), :method => "get" %></td>
                  <td><%= button_to "Show Contacts" , apn_contacts_url(apn), :method => "get" %></td>
                  <td><%= button_to "Show Node Information", apn_nodes_url(apn), :method =>"get" %></td>
                </tr>
              <% end %>
          <% end %>
          </tbody>
      </table>
    </ul>
  </div>
</div>

app/views/apns/new.html.erb
<h1>Custom APN Form</h1>
<p>Please fill out the sections below</p>

<%= form_for @apn do |f| %>
    <% if @apn.errors.any? %>
        <div class="error_messages">
          <h2>Apn Form is invalid</h2>
          <ul>
            <% for message in @apn.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :company_name, 'Company Name' %>
      <%= f.text_field :company_name %>
    </p>
    <p>
      <%= f.label :project_name %>
      <%= f.text_field :project_name %>
    </p>
    <p>
      <%= f.label :project_number %>
      <%= f.text_field :project_number %>
    </p>

    <p>
      <%= f.label :apn_name, "APN Name" %>
      <%= f.text_field :apn_name %>
    </p>
    <p>
      <%= f.label :static_ip, "Static IP Required?" %>
      <%= f.check_box :static_ip %>
    </p>
    <p>
      <%= f.label :control_center, "Control Center Required?" %>
      <%= f.check_box :control_center %>

    </p>
    <% if current_user.administrator? %>
        <p>
          <%= f.label :control_center_account_name, "Control Center Account Name:" %>
          <%= f.text_field :control_center_account_name %>
        </p>
        <p>
          <%= f.label :control_center_account_id, "Control Center Account ID:" %>
          <%= f.text_field :control_center_account_id %>
        </p>
        <p>
        <%= f.select :radius_jasper_proxy_filter, options_for_select([
                                                                  "Default: Forward Radius traffic to Control Centre based on Jasper dedicated IMSIs only",
                                                                  "Change: Modify Radius to add IMSI filtering for Jasper"
                                                          ])%>
    <% end %>

    <%= f.submit "Submit" %>
<% end %>

app/views/apns/show.html.erb
<h1 xmlns="http://www.w3.org/1999/html"><%= @apn.company_name %> <%= @apn.apn_name %> APN Form</h1>


<dl class="tabs" data-tab>
  <dd class="active"><a href="#panel1">Main APN Information</a></dd>
  <dd><a href="#panel2">Contact Information</a></dd>
  <dd><a href="#panel3">Tunnel Information</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="panel1">
    <p>
    <div class="large-6 columns">
      <div class="panel">
        <h4>Main APN Information</h4>
          <p>
            <strong>Project Name:</strong> <%= @apn.project_name%><br>
            <strong>Project Number:</strong> <%= @apn.project_number %><br>
            <strong>APN Name:</strong> <%= @apn.apn_name %><br>
            <strong>Rogers APN ID:</strong> <%= @apn.rogers_apn_id %><br>
            <strong>Fido APN ID:</strong><%= @apn.fido_apn_id %><br>
            <strong>Redundancy Type:</strong><br>
            <%= @apn.redundancy_type %><br>
            <br>
            <strong>Mobile to Mobile Communications:</strong><br>
            <%= @apn.m2m_communications %><br>
            <br>
            <% if @apn.static_ip? %>
                <strong>APN Type:</strong> Static IP<br>
            <% else %>
                <strong>APN Type:</strong> Dynamic IP<br>
            <% end %>
            <br>
            <strong>Context ID:</strong> <%= @apn.context_id %><br>
            <strong>Max download rate:</strong> 250000000<br>
            <strong>Max upload rate:</strong> 100000000<br>
            <strong>QoS profile (HSS-EsmQosProfileQci):</strong> 8<br>
            <strong>Priority (HSS-EsmQosProfileArp):</strong> 10<br>
            <strong>Charging Chars (HSS-EsmEpsBearerChargingChars):</strong> 9<br>
            <strong>PDN Type:</strong> V4  OR V6 or Dual stack V4V6 <br>
            <br>
            <% if @apn.control_center? %>
                <strong>Contact Center:</strong> Yes<br>
                <strong>Control Center Account Name:</strong> <%= @apn.control_center_account_name %><br>
                <strong>Control Center Account ID:</strong <%= @apn.control_center_account_id %><br>
                <strong>Radius Jasper Proxy Filter:</strong>
                <%= @apn.radius_jasper_proxy_filter %><br>
            <% else %>
                Control Center: No
            <% end %>
          </p>
  </div>
</div>


</p>
  </div>
  <div class="content" id="panel2">
    <div class="large-6 columns">
      <div class="panel">
        <h4>Contact Information</h4>
        <p>
          <% @apn.contacts.each do |c| %>
              <%if c.technical_contact? %>
                  <strong>Technical Contact:</strong><br>
              <% else%>
                  <strong>Business Contact:</strong><br>
              <% end %>
              <strong>Contact Name:</strong><br>
              <%= c.name %><br>
              <strong>Email Address:</strong><br>
              <%= c.email %>
              <strong>Company Name: </strong><br>
              <%= c.company_name %>
              <hr>
          <% end %>
        </p>
        </div>
      </div>
  </div>
  <div class="content" id="panel3">
    <div class="large-6 columns">
      <div class="panel">
        <h4>Tunnel Information</h4>
        <p>
        <% @apn.nodes.each do |n| %>
            <div><strong>Node Location:</strong> <%= n.ssr_location %></div>
            <hr>
            <% n.tunnels.each do |t| %>
                <p>
                  <strong>Tunnel Information:</strong><br><br>
                  <strong>Rogers Mobile Device IP Range:</strong> <%= t.rogers_mobile_ip %><br>
                  <strong>Customer Server/GRE Endpoint IP's:</strong> <%= t.customer_server_ip %><br>
                  <strong>Rogers VPN Tunnel Endpoint:</strong> <%= t.rogers_vpn_ip %><br>
                  <strong>Customer VPN Tunnel Endpoint IP:</strong> <%= t.customer_vpn_ip %><br>
                  <br>
                  <br>
            <% end %>
        <% end %>
        </p>
        <hr>
        </div>
      </div>
  </div>
</div>