config/routes.rb
Rails.application.routes.draw do

  resources :apns, only: [:new, :create, :show, :index, :edit, :update]
  resources :apns do
    resources :contacts
    resources :nodes do
      resources :tunnels do
        resources :tunnel_rules
        end
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:create, :destroy, :new]
  resources :users do
    member do
      get :activate
    end
  end

  root 'apns#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get "signup" => "users#new", :as => "signup"
  get 'deletenode' => 'nods#destroy',:as => 'deletenode'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :apn
  belongs_to :tunnel
  belongs_to :user

  # makes sure that the user has an email address, first name and last name.
  # validates_presence_of :email, :first_name, :last_name
  # validates_format_of :phone_number1, :with => /\d{3}[ -.]?\d{3}[ -.]?\d{4}/, :message => 'Phone number must be in the format XXX-XXX-XXXX. Dashes/spaces/dots optional'
  # validates_format_of :phone_number2, :with => /\d{3}[ -.]?\d{3}[ -.]?\d{4}/, :message => 'Phone number must be in the format XXX-XXX-XXXX. Dashes/spaces/dots optional'
  def name
    [first_name,last_name].join(' ')
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # this is a CanCan thing, to check to see if you're logged in before you can do anything on this page.
  load_and_authorize_resource

  # required to be logged in to be able to see the page.
  before_action :require_login

  def index
    @apn = Apn.find(params[:apn_id])
    @contacts = @apn.contacts.order(id: :asc).all
  end

  def show
    @contacts = Contact.order(id: :asc).all
  end

  def new
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    # make sure that when you create a new contact that you pass in the APN ID into the @contact (note it says contacts and not contact)
    @contact = @apn.contacts.build
  end

  def create
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    # make sure that when you create a new contact that you pass in the APN ID into the @contact (note it says contacts and not contact) You'll be passing the contact_params method
    @contact = @apn.contacts.build(contact_params)
    if @contact.save
      redirect_to apn_contacts_path
    else
      render :new
    end
  end

  def edit
    # makes sure that you find the right APN ID for that new contact first
    @apn = Apn.find(params[:apn_id])
    # make sure that when you create a new contact that you pass in the APN ID into the @contact (note it says contacts and not contact) You'll be passing the contact_params method
    @contact = @apn.contacts.find(params[:id])
  end

  def update
    if @contact.update_attributes(contact_params)
      redirect_to apn_contacts_path, notice: 'Successfully Updated the APN Contact'
    else
      render :edit
    end
  end

  def destroy
    # makes sure that you find the right APN ID for that contact first
    @apn = Apn.find(params[:apn_id])
    @node = @apn.contacts.find(params[:id])
    @contact.destroy
    redirect_to apn_contacts_path, notice: 'Contact was deleted'
  end
  private
  def contact_params
    params.require(:contact).permit(
        :first_name,
        :last_name,
        :company_name,
        :street_address,
        :city,
        :province_state,
        :country,
        :email,
        :phone_number1,
        :phone_number2,
        :technical_contact,
        :business_contact
    )
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/edit.html.erb
<h1>Edit APN Contact</h1>
<%= form_for [@apn, @contact] do |f| %>
    <% if @contact.errors.any? %>
        <div class="error_messages">
          <h2>Contact Information is invalid</h2>
          <ul>
            <% for message in @contact.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :business_contact %>
      <%= f.check_box :business_contact %>
    </p>
    <p>
      <%= f.label :technical_contact %>
      <%= f.check_box :technical_contact %>
    </p>
    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </p>
    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </p>
    <p>
      <%= f.label :company_name %>
      <%= f.text_field :company_name %>
    </p>
    <p>
      <%= f.label :street_address %>
      <%= f.text_field :street_address %>
    </p>
    <p>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :province_state, 'Province/State' %>
      <%= f.text_field :province_state %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :phone_number1, 'Main Phone' %>
      <%= f.text_field :phone_number1 %>
    </p>
    <p>
      <%= f.label :phone_number2, 'Cell Phone' %>
      <%= f.text_field :phone_number2 %>
    </p>
    <%= f.submit "Save Changes"%>
    <%= button_to "Cancel", apn_contacts_url, :method => "get" %>
<% end %>

app/views/contacts/index.html.erb
<h1>Contact Information for APN:<%= @apn.apn_name %></h1>

<div class="row">
    <div class="large-6 columns">
      <ul>
        <table class="Contact Table">
          <thead>
          <th>Contact Name:</th>
          <th>Contact Type:</th>
          <th>Edit APN Contact Information:</th>
          <th>Delete Contact</th>
          </thead>
          <tbody>
              <% @contacts.each do |c| %>
                  <tr>
                    <td><%= c.name %></td>
                    <td>
                      <%if c.technical_contact? %>
                              Technical Contact
                      <% else %>
                          Business Contact
                      <% end %>
                    </td>
                          <!--pass in the @contact.apn_id and @contact.id into the edit_apn_contact_path-->
                    <td><%= button_to "Edit contact" , edit_apn_contact_path(c.apn_id, c.id), :method => "get" %></td>
                          <td><%= button_to "Delete", apn_contact_path(c.apn_id, c.id), :method => "delete", data: { confirm: "Are you sure you want delete this node?" } %></td>
                  </tr>
          <% end %>
          </tbody>
        </table>
        <%= button_to "Add Contact", new_apn_contact_path(@apn), :method => "get" %>
      </ul>
      <%= button_to "Back", apns_url, :method => "get" %>
    </div>
</div>

app/views/contacts/new.html.erb
<!--passed in an array that takes the @apn (:apn_id), @contact objects there were declared from the contact controller def new -->
<div class="row">
  <div class="large-6 columns">
    <%= form_for [@apn, @contact] do |f| %>
        <% if @contact.errors.any? %>
            <div class="error_messages">
              <h2>Contact Information is invalid</h2>
              <ul>
                <% for message in @contact.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <p>
          <%= f.label :business_contact %>
          <%= f.check_box :business_contact %>
        </p>
        <p>
          <%= f.label :technical_contact %>
          <%= f.check_box :technical_contact %>
        </p>
        <p>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </p>
        <p>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </p>
        <p>
          <%= f.label :company_name %>
          <%= f.text_field :company_name %>
        </p>
        <p>
          <%= f.label :street_address %>
          <%= f.text_field :street_address %>
        </p>
        <p>
          <%= f.label :city %>
          <%= f.text_field :city %>
        </p>
        <p>
          <%= f.label :province_state %>
          <%= f.text_field :province_state %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.text_field :email %>
        </p>
        <p>
          <%= f.label 'Main Phone' %>
          <%= f.text_field :phone_number1 %>
        </p>
        <p>
          <%= f.label 'Cell Phone' %>
          <%= f.text_field :phone_number2 %>
        </p>
        <%= f.submit "Add Contact"%>
    <% end %>
   </div>
  <%= button_to "Cancel", apn_contacts_url, :method => "get" %>
</div>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>