config/routes.rb
Rails.application.routes.draw do

  resources :apns, only: [:new, :create, :show, :index, :edit, :update]
  resources :apns do
    resources :contacts
    resources :nodes do
      resources :tunnels do
        resources :tunnel_rules
        end
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:create, :destroy, :new]
  resources :users do
    member do
      get :activate
    end
  end

  root 'apns#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get "signup" => "users#new", :as => "signup"
  get 'deletenode' => 'nods#destroy',:as => 'deletenode'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Rogers Custom APN" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="fixed">
      <nav id="red-style" class="top-bar" data-topbar>
        <ul class="title-area">

          <li class="name">
            <h1>
              <a href="#">Rogers Custom APN Website</a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section id="red-style" class="top-bar-section">
              <ul class="left">
                <li id="red-style" class="divider"></li>
                <li class="has-dropdown">
                  <!--check to see if the user is logged in-->
                  <% if logged_in? %>
                  <!--if the user is an administrator they will log in and have the following menus-->
                          <% if current_user.administrator? %>
                              <a id="red-style" class="active" href="#">Administrative Options</a>
                                  <ul id="red-style" class="dropdown">
                                      <!--<li><label>Administrative Options</label></li>-->
                                      <li><%= link_to "APN index page", apns_path, html_options = { :id => "red-style" } %></li>
                                      <li><%= link_to "Add new user", new_user_path, html_options = { :id => "red-style" }  %></a></li>
                                      <li><%= link_to "Add new APN", new_apn_path, html_options = { :id => "red-style" }  %></li>
                                  </ul>
                                <!--if the user is not an administrator they will see this following menu-->
                          <% else %>
                              <a class="active" href="#">User options</a>
                              <ul class="dropdown">
                                  <li><%= link_to "APN index page", apns_path, html_options = { :id => "red-style" }  %></a></li>
                                  <li><%= link_to "Add new APN", new_apn_path, html_options = { :id => "red-style" }  %></a></li>
                              </ul>
                          <% end %>
                  <% end %>
              </ul>
          <ul class="right">
            <li class="divider"></li>
            <li class="has-dropdown">
              <% if current_user %>
                  <a id="red-style" href="#"><%= current_user.name %></a>
                  <ul class="dropdown">
                    <li><%= link_to "Log Out", :logout, html_options = { :id => "red-style" } %></li>
                  </ul>
                <% end %>
            </li>
          </ul>
        </section>
      </nav>
    </div>


    <div class="container">
      <% flash.each do |name, message| %>
          <div> <%= [name, message] %></div>
      <% end %>

      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>